# Generated by Django 4.1.7 on 2023-03-08 10:03

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Baby',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('last_modified', models.DateTimeField(auto_now=True)),
                ('archived', models.BooleanField(default=False)),
                ('name', models.CharField(max_length=150)),
                ('gender', models.CharField(choices=[('f', 'Female'), ('m', 'Male')], max_length=1)),
                ('dob', models.DateTimeField()),
                ('time_of_birth', models.TimeField()),
                ('due_day', models.DateField(null=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='babies', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'Babies',
            },
        ),
    ]
